// @generated by scripts/generate-vtdf.mjs. Do not edit directly.
export const componentRoutes = [
	{
		nav: 'accordion',
		component: 'Accordion'
	},
	{
		nav: 'actionPopover',
		component: 'ActionPopover'
	},
	{
		nav: 'actionSheet',
		component: 'ActionSheet'
	},
	{
		nav: 'alert',
		component: 'Alert'
	},
	{
		nav: 'asyncPicker',
		component: 'AsyncPicker'
	},
	{
		nav: 'avatar',
		component: 'Avatar'
	},
	{
		nav: 'avatarGroup',
		component: 'AvatarGroup'
	},
	{
		nav: 'badge',
		component: 'Badge'
	},
	{
		nav: 'bottomSheet',
		component: 'BottomSheet'
	},
	{
		nav: 'button',
		component: 'Button'
	},
	{
		nav: 'buttonGroup',
		component: 'ButtonGroup'
	},
	{
		nav: 'calendar',
		component: 'Calendar'
	},
	{
		nav: 'card',
		component: 'Card'
	},
	{
		nav: 'cell',
		component: 'Cell'
	},
	{
		nav: 'charRoll',
		component: 'CharRoll'
	},
	{
		nav: 'checkbox',
		component: 'Checkbox'
	},
	{
		nav: 'codeInput',
		component: 'CodeInput'
	},
	{
		nav: 'colorPicker',
		component: 'ColorPicker'
	},
	{
		nav: 'countDown',
		component: 'CountDown'
	},
	{
		nav: 'dialog',
		component: 'Dialog'
	},
	{
		nav: 'divider',
		component: 'Divider'
	},
	{
		nav: 'feedback',
		component: 'Feedback'
	},
	{
		nav: 'form',
		component: 'Form'
	},
	{
		nav: 'fullKeyboard',
		component: 'FullKeyboard'
	},
	{
		nav: 'grids',
		component: 'Grids'
	},
	{
		nav: 'icon',
		component: 'Icon'
	},
	{
		nav: 'imageList',
		component: 'ImageList'
	},
	{
		nav: 'imagePreview',
		component: 'ImagePreview'
	},
	{
		nav: 'indexBar',
		component: 'IndexBar'
	},
	{
		nav: 'infiniteScroll',
		component: 'InfiniteScroll'
	},
	{
		nav: 'input',
		component: 'Input'
	},
	{
		nav: 'list',
		component: 'List'
	},
	{
		nav: 'loading',
		component: 'Loading'
	},
	{
		nav: 'mask',
		component: 'Mask'
	},
	{
		nav: 'modal',
		component: 'Modal'
	},
	{
		nav: 'navBar',
		component: 'NavBar'
	},
	{
		nav: 'noticeBar',
		component: 'NoticeBar'
	},
	{
		nav: 'numKeyboard',
		component: 'NumKeyboard'
	},
	{
		nav: 'pagination',
		component: 'Pagination'
	},
	{
		nav: 'picker',
		component: 'Picker'
	},
	{
		nav: 'placeholder',
		component: 'Placeholder'
	},
	{
		nav: 'popup',
		component: 'Popup'
	},
	{
		nav: 'progress',
		component: 'Progress'
	},
	{
		nav: 'progressLoop',
		component: 'ProgressLoop'
	},
	{
		nav: 'pullRefresh',
		component: 'PullRefresh'
	},
	{
		nav: 'radio',
		component: 'Radio'
	},
	{
		nav: 'rate',
		component: 'Rate'
	},
	{
		nav: 'signature',
		component: 'Signature'
	},
	{
		nav: 'skeleton',
		component: 'Skeleton'
	},
	{
		nav: 'slider',
		component: 'Slider'
	},
	{
		nav: 'stepper',
		component: 'Stepper'
	},
	{
		nav: 'steps',
		component: 'Steps'
	},
	{
		nav: 'swiper',
		component: 'Swiper'
	},
	{
		nav: 'switch',
		component: 'Switch'
	},
	{
		nav: 'tabBar',
		component: 'TabBar'
	},
	{
		nav: 'tabs',
		component: 'Tabs'
	},
	{
		nav: 'tag',
		component: 'Tag'
	},
	{
		nav: 'timePicker',
		component: 'TimePicker'
	},
	{
		nav: 'toast',
		component: 'Toast'
	},
	{
		nav: 'tooltip',
		component: 'Tooltip'
	}
] as const;
