import {
	Badge as BadgeIcon,
	BellRing,
	Binary,
	Box,
	Braces,
	CalendarDays,
	CaseSensitive,
	ChartNoAxesColumnIncreasing,
	ChevronsUpDown,
	CircleDot,
	CirclePlus,
	Clock3,
	Compass,
	CreditCard,
	Ellipsis,
	GalleryHorizontal,
	GalleryHorizontalEnd,
	Grid2X2,
	Grid3X3,
	Image as ImageIcon,
	ImageOff,
	Images,
	Keyboard,
	LayoutGrid,
	List,
	ListChecks,
	ListCollapse,
	ListFilter,
	ListOrdered,
	ListStart,
	ListTodo,
	LoaderCircle,
	Megaphone,
	MessageCircleReply,
	MessageCircleWarning,
	MessagesSquare,
	MessageSquareMore,
	MessageSquareText,
	Minus,
	MousePointerClick,
	PanelBottom,
	PanelsTopLeft,
	PanelTop,
	PenLine,
	Pipette,
	RefreshCw,
	Rows2,
	Rows3,
	Scan,
	ScanSearch,
	Shapes,
	SlidersHorizontal,
	SquareArrowOutUpRight,
	SquareCheck,
	Star,
	Tag,
	TextCursorInput,
	Timer,
	ToggleLeft,
	TriangleAlert,
	UserRound,
	UsersRound
} from '@lucide/svelte';

export const fallbackComponentIcon = Box;

export const categoryIconMap = {
	基础: Box,
	弹层基础: PanelsTopLeft,
	操作弹层: Rows3,
	布局: LayoutGrid,
	导航: Compass,
	表单与输入: TextCursorInput,
	选择控件: ListChecks,
	选择器: SlidersHorizontal,
	列表与单元格: List,
	数据展示: ChartNoAxesColumnIncreasing,
	媒体: ImageIcon,
	反馈: MessageCircleWarning,
	函数式: Braces
};

export const componentIconMap = {
	button: MousePointerClick,
	buttonGroup: PanelsTopLeft,
	icon: Shapes,
	bottomSheet: PanelBottom,
	mask: Scan,
	popup: SquareArrowOutUpRight,
	actionPopover: MessageSquareMore,
	actionSheet: ListCollapse,
	card: CreditCard,
	divider: Minus,
	grids: Grid3X3,
	placeholder: ImageOff,
	skeleton: GalleryHorizontalEnd,
	indexBar: ListOrdered,
	navBar: PanelTop,
	pagination: Ellipsis,
	steps: ListStart,
	tabBar: PanelBottom,
	tabs: Rows3,
	codeInput: Binary,
	form: ListTodo,
	fullKeyboard: Keyboard,
	input: TextCursorInput,
	numKeyboard: Grid2X2,
	signature: PenLine,
	checkbox: SquareCheck,
	radio: CircleDot,
	rate: Star,
	slider: SlidersHorizontal,
	stepper: CirclePlus,
	switch: ToggleLeft,
	asyncPicker: ListFilter,
	calendar: CalendarDays,
	colorPicker: Pipette,
	picker: ListFilter,
	timePicker: Clock3,
	accordion: ChevronsUpDown,
	cell: Rows2,
	list: List,
	pullRefresh: RefreshCw,
	infiniteScroll: LoaderCircle,
	avatar: UserRound,
	avatarGroup: UsersRound,
	badge: BadgeIcon,
	charRoll: CaseSensitive,
	countDown: Timer,
	noticeBar: Megaphone,
	progress: ChartNoAxesColumnIncreasing,
	progressLoop: LoaderCircle,
	tag: Tag,
	tooltip: MessageSquareText,
	imagePreview: ScanSearch,
	imageList: Images,
	swiper: GalleryHorizontal,
	alert: TriangleAlert,
	dialog: MessagesSquare,
	loading: LoaderCircle,
	modal: PanelsTopLeft,
	toast: BellRing,
	feedback: MessageCircleReply
};
