import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const workspaceRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const stdfRoutesRoot = join(workspaceRoot, 'apps/stdf-demo/src/routes');
const outputPath = join(workspaceRoot, 'apps/vtdf-demo/src/componentRoutes.ts');
const checkOnly = process.argv.includes('--check');

const generatedHeader = '// @generated by scripts/generate-vtdf.mjs. Do not edit directly.\n';

const componentRoutes = readdirSync(stdfRoutesRoot, { withFileTypes: true })
	.filter((entry) => {
		if (!entry.isDirectory() || entry.name === 'components') return false;
		return (
			existsSync(join(stdfRoutesRoot, entry.name, 'zh_CN/+page.svelte')) &&
			existsSync(join(stdfRoutesRoot, entry.name, 'en_US/+page.svelte'))
		);
	})
	.map((entry) => ({
		nav: entry.name,
		component: `${entry.name.charAt(0).toUpperCase()}${entry.name.slice(1)}`
	}))
	.sort((left, right) => left.nav.localeCompare(right.nav));

const output = `${generatedHeader}export const componentRoutes = [\n${componentRoutes
	.map(({ nav, component }) => `\t{\n\t\tnav: '${nav}',\n\t\tcomponent: '${component}'\n\t}`)
	.join(',\n')}\n] as const;\n`;
const current = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : '';

if (checkOnly) {
	if (current !== output) {
		console.error(`Generated file is stale: ${outputPath}`);
		process.exit(1);
	}
	console.log(`PASS generated route manifest (${componentRoutes.length} components)`);
} else if (current === output) {
	console.log(`No generated changes (${componentRoutes.length} components)`);
} else {
	writeFileSync(outputPath, output);
	console.log(`Updated ${outputPath} (${componentRoutes.length} components)`);
}
