import type { Component } from 'vue';
import {
	ArrowRight,
	Badge as BadgeIcon,
	BellRing,
	Binary,
	Blocks,
	BookOpen,
	Box,
	Boxes,
	Braces,
	BrainCircuit,
	CalendarDays,
	CaseSensitive,
	ChartNoAxesColumnIncreasing,
	ChevronsUpDown,
	CircleArrowUp,
	CircleDot,
	CircleEllipsis,
	CirclePlus,
	CircleQuestionMark,
	Clock3,
	Compass,
	CreditCard,
	Ellipsis,
	FileText,
	GalleryHorizontal,
	GalleryHorizontalEnd,
	Gem,
	GitPullRequest,
	Goal,
	Grid2X2,
	Grid3X3,
	History,
	Image as ImageIcon,
	ImageOff,
	Images,
	Info,
	Keyboard,
	Languages,
	LayoutGrid,
	List,
	ListChecks,
	ListCollapse,
	ListFilter,
	ListOrdered,
	ListStart,
	ListTodo,
	LoaderCircle,
	Megaphone,
	MessageCircleReply,
	MessageCircleWarning,
	MessagesSquare,
	MessageSquareMore,
	MessageSquareText,
	Minus,
	MonitorCheck,
	MousePointerClick,
	Palette,
	PanelBottom,
	PanelsTopLeft,
	PanelTop,
	PenLine,
	Pipette,
	Puzzle,
	RefreshCw,
	Rocket,
	Rows2,
	Rows3,
	Scan,
	ScanSearch,
	Shapes,
	SlidersHorizontal,
	SquareArrowOutUpRight,
	SquareCheck,
	Star,
	SunMoon,
	Tag as TagIcon,
	Telescope,
	Terminal,
	TextCursorInput,
	Timer,
	ToggleLeft,
	TriangleAlert,
	UserRound,
	UsersRound,
	WandSparkles,
	Wrench,
	Zap
} from 'lucide-vue-next';
import { componentCategoryIconMap, componentIconMap, guideCategoryIconMap, guideItemIconMap } from '@any-tdf/site-common/data';

// Lucide 图标名 → 组件的静态注册表（保持可 tree-shake，键名与 @any-tdf/site-common/data 的图标映射一致）。
const lucideIconRegistry: Record<string, Component> = {
	ArrowRight,
	Badge: BadgeIcon,
	BellRing,
	Binary,
	Blocks,
	BookOpen,
	Box,
	Boxes,
	Braces,
	BrainCircuit,
	CalendarDays,
	CaseSensitive,
	ChartNoAxesColumnIncreasing,
	ChevronsUpDown,
	CircleArrowUp,
	CircleDot,
	CircleEllipsis,
	CirclePlus,
	CircleQuestionMark,
	Clock3,
	Compass,
	CreditCard,
	Ellipsis,
	FileText,
	GalleryHorizontal,
	GalleryHorizontalEnd,
	Gem,
	GitPullRequest,
	Goal,
	Grid2X2,
	Grid3X3,
	History,
	Image: ImageIcon,
	ImageOff,
	Images,
	Info,
	Keyboard,
	Languages,
	LayoutGrid,
	List,
	ListChecks,
	ListCollapse,
	ListFilter,
	ListOrdered,
	ListStart,
	ListTodo,
	LoaderCircle,
	Megaphone,
	MessageCircleReply,
	MessageCircleWarning,
	MessagesSquare,
	MessageSquareMore,
	MessageSquareText,
	Minus,
	MonitorCheck,
	MousePointerClick,
	Palette,
	PanelBottom,
	PanelsTopLeft,
	PanelTop,
	PenLine,
	Pipette,
	Puzzle,
	RefreshCw,
	Rocket,
	Rows2,
	Rows3,
	Scan,
	ScanSearch,
	Shapes,
	SlidersHorizontal,
	SquareArrowOutUpRight,
	SquareCheck,
	Star,
	SunMoon,
	Tag: TagIcon,
	Telescope,
	Terminal,
	TextCursorInput,
	Timer,
	ToggleLeft,
	TriangleAlert,
	UserRound,
	UsersRound,
	WandSparkles,
	Wrench,
	Zap
};

export { ArrowRight, Box, Boxes, Gem, Palette, SlidersHorizontal, SunMoon, WandSparkles, Zap };

export const fallbackIcon = Box;

/** 按 Lucide 图标名解析组件，未注册时回退到 fallback 图标。 */
export const getLucideIcon = (name: string | undefined): Component => (name && lucideIconRegistry[name]) || fallbackIcon;

/** 组件分类图标，key 为 menuList 的 class 字段。 */
export const getComponentCategoryIcon = (name: string): Component => getLucideIcon(componentCategoryIconMap[name]);

/** 组件图标，key 为 menuList 的 nav 字段。 */
export const getComponentIcon = (nav: string): Component => getLucideIcon(componentIconMap[nav]);

/** 指南分类图标，key 为 guideMenuList 的 class 字段。 */
export const getGuideCategoryIcon = (name: string): Component => getLucideIcon(guideCategoryIconMap[name]);

/** 指南条目图标，key 为 guideMenuList 的 nav 字段。 */
export const getGuideItemIcon = (nav: string): Component => getLucideIcon(guideItemIconMap[nav]);
